version: '3.2'

services:

  # Computation
  jupyterlab:
    container_name: "jupyterlab"
    restart: "always"
    build: services/jupyter
    env_file:
      - ./config/jupyter.env
#      - ./config/minio.env
#      - ./config/shared_database.env
    volumes:
      - ./shared/notebooks/:/home/jovyan/notebooks
    ports:
      - 9999:8888
    entrypoint: sh -c 'jupyter lab --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX} --NotebookApp.token=$$JUPYTER_PASSWORD'

  mongodb:
    container_name: "mongodb"
    image: mongo:3.6.2
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./config/mongodb.env
    volumes:
      - ~/data-volume/mongodb_data:/data-volume/db

  oracle11g:
    container_name: oracle11g
    image: oracleinanutshell/oracle-xe-11g:latest
    restart: always
    env_file:
      - ./config/oracle.env
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./services/oracle/init:/docker-entrypoint-initdb.d
      - ~/data-volume/oradata:/opt/oracle/oradata # jaspeen/oracle-xe-11g

  mysql:
    container_name: "mysql"
    image: mysql:5.7
    restart: always
    env_file:
      - ./config/mysql.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data-volume will be persisted
    volumes:
      - ./services/mysql/init:/docker-entrypoint-initdb.d
      - ~/data-volume/mysql-db:/var/lib/mysql

#  # Misc Storage
#  postgres:
#    container_name: "postgres"
#    restart: "always"
#    image: postgres
#    env_file:
#      - ./config/postgres.env
#      # - ./config/superset_database.env
#      # - ./config/airflow_database.env
#      - ./config/shared_database.env
#    volumes:
#      - ~/data-volume/postgres_data:/var/lib/postgresql/data-volume/
#      - ./services/postgres/:/docker-entrypoint-initdb.d/
#    ports:
#      - 5432:5432

#  # Model Storage
#  minio:
#    container_name: "minio"
#    restart: "always"
#    image: minio/minio
#    env_file:
#      - ./config/minio.env
#    volumes:
#      - minio_volume:/data-volume
#    ports:
#      - 9000:9000
#    command: server /data-volume

#  # Admin Overview
#  portainer:
#    container_name: "portainer"
#    restart: "always"
#    image: portainer/portainer
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_volume:/data-volume
#    ports:
#      - 9090:9000
#    command: -H unix:///var/run/docker.sock

networks:
  elk:
    driver: bridge

# Volumes to persist data-volume
#volumes:
#  minio_volume:
#  portainer_volume: